import type { Feedback, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

const users: User[] = [
  { id: 'user-1', name: 'Sarah Johnson', avatarUrl: PlaceHolderImages.find(p => p.id === 'avatar-1')?.imageUrl || '' },
  { id: 'user-2', name: 'Mike Thompson', avatarUrl: PlaceHolderImages.find(p => p.id === 'avatar-2')?.imageUrl || '' },
  { id: 'user-3', name: 'Jane Doe', avatarUrl: PlaceHolderImages.find(p => p.id === 'avatar-3')?.imageUrl || '' },
  { id: 'user-4', name: 'Chris Evans', avatarUrl: PlaceHolderImages.find(p => p.id === 'avatar-4')?.imageUrl || '' },
];

export const mockFeedback: Feedback[] = [
  {
    id: 'fb-1',
    title: 'Dark mode for the entire application',
    description: 'It would be great to have a dark mode option to reduce eye strain, especially when working at night. It should be easily toggleable from the user settings.',
    status: 'planned',
    category: 'Feature Request',
    tags: ['ui', 'dark-mode'],
    author: users[0],
    createdAt: '2 days ago',
    voteCount: 128,
    commentCount: 12,
  },
  {
    id: 'fb-2',
    title: 'Integration with Slack for notifications',
    description: 'We use Slack for all our team communication. Getting notifications about new feedback, comments, and status changes directly in a designated Slack channel would be a huge productivity boost.',
    status: 'in-progress',
    category: 'Integration',
    tags: ['notifications', 'slack'],
    author: users[1],
    createdAt: '5 days ago',
    voteCount: 95,
    commentCount: 8,
  },
  {
    id: 'fb-3',
    title: 'Image upload fails on mobile sometimes',
    description: 'When I try to upload a screenshot from my phone (iOS 17), it occasionally fails without an error message. It seems to happen more often with larger images.',
    status: 'open',
    category: 'Bug',
    tags: ['mobile', 'upload'],
    author: users[2],
    createdAt: '1 hour ago',
    voteCount: 12,
    commentCount: 3,
  },
  {
    id: 'fb-4',
    title: 'Ability to merge duplicate feedback posts',
    description: 'As an admin, I often see multiple users submitting the same idea. I\'d love a feature to merge these duplicates into a single post, consolidating all the votes and comments.',
    status: 'completed',
    category: 'Feature Request',
    tags: ['admin', 'moderation'],
    author: users[3],
    createdAt: '1 month ago',
    voteCount: 250,
    commentCount: 45,
  },
    {
    id: 'fb-5',
    title: 'Improve the search functionality with filters',
    description: 'The current search is good, but it would be amazing to filter results by status, category, and tags directly from the search bar.',
    status: 'open',
    category: 'Improvement',
    tags: ['search', 'filters'],
    author: users[0],
    createdAt: '3 days ago',
    voteCount: 45,
    commentCount: 6,
  },
  {
    id: 'fb-6',
    title: 'Public roadmap is not responsive on small screens',
    description: 'When viewing the roadmap on my phone, the columns are too wide and require horizontal scrolling, which is not a great experience. It should stack vertically.',
    status: 'open',
    category: 'Bug',
    tags: ['roadmap', 'responsive'],
    author: users[1],
    createdAt: '1 day ago',
    voteCount: 8,
    commentCount: 1,
  },
];
